swagger: "2.0"
info:
  version: "1.0.0"
  title: "Auth API"
tags:
  - name: "Category"
    description: "Category Modules and  Routes"
paths:
  /category:
    post:
      summary: "Create new category"
      tags:
        - "Category"
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: "#/components/schemas/CreateCategory"
          application/json:
            schema:
              $ref: "#/components/schemas/CreateCategory"
      responses:
        200:
          description: "Successful request"
/category:
  get:
    summary: "Get all categories"
    tags:
      - "Category"
    responses:
      200:
        description: "Successful request"
components:
  schemas:
    CreateCategory:
      type: "object"
      required:
        - "name"
        - "icon"
      properties:
        name:
          type: "string"
        icon:
          type: "string"
        slug:
          type: "string"
        parent:
          type: "string"
